"""Daily log management for GitHub Streak AI.

Handles creation, reading, updating, and listing of daily markdown logs
stored in the logs/YYYY/MM/YYYY-MM-DD.md directory structure.
"""

from __future__ import annotations

import logging
import re
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader, TemplateNotFound

from config.constants import (
    DAILY_LOG_TEMPLATE,
    DATE_FORMAT,
    DISPLAY_DATE_FORMAT,
    LOG_FILENAME_PATTERN,
    LOG_SECTIONS,
)
from config.settings import Settings, get_settings

logger = logging.getLogger(__name__)


class LogError(Exception):
    """Base exception for log operations."""


class LogNotFoundError(LogError):
    """Raised when a requested log file does not exist."""


class LogCorruptedError(LogError):
    """Raised when a log file cannot be parsed correctly."""


class LogManager:
    """Manages daily markdown log files.

    Logs are stored in a hierarchical directory structure:
        logs/YYYY/MM/YYYY-MM-DD.md

    Each log contains sections defined in LOG_SECTIONS and can be
    populated via Jinja2 templates or programmatically.

    Example:
        >>> manager = LogManager()
        >>> path = manager.create_daily_log()
        >>> print(f"Created: {path}")
    """

    def __init__(self, settings: Settings | None = None) -> None:
        """Initialize the LogManager.

        Args:
            settings: Application settings. If None, loads from environment.
        """
        self._settings = settings or get_settings()
        self._logs_dir = self._settings.logs_dir
        self._logs_dir.mkdir(parents=True, exist_ok=True)

        # Set up Jinja2 environment
        templates_dir = self._settings.templates_dir
        if templates_dir.exists():
            self._jinja_env = Environment(
                loader=FileSystemLoader(str(templates_dir)),
                keep_trailing_newline=True,
                trim_blocks=True,
                lstrip_blocks=True,
            )
        else:
            self._jinja_env = None
            logger.warning(
                "Templates directory not found at %s. Using fallback template.",
                templates_dir,
            )

    def _get_log_path(self, target_date: date) -> Path:
        """Build the file path for a given date.

        Args:
            target_date: The date to build a path for.

        Returns:
            Full path to the log file.
        """
        relative = LOG_FILENAME_PATTERN.format(
            year=target_date.year,
            month=target_date.month,
            day=target_date.day,
        )
        return self._logs_dir / relative

    def _render_template(self, target_date: date) -> str:
        """Render the daily log template for the given date.

        Falls back to a built-in template if Jinja2 templates aren't available.

        Args:
            target_date: The date to render the template for.

        Returns:
            Rendered markdown content.
        """
        context = {
            "date": target_date.strftime(DATE_FORMAT),
            "display_date": target_date.strftime(DISPLAY_DATE_FORMAT),
            "day_of_week": target_date.strftime("%A"),
            "sections": LOG_SECTIONS,
        }

        if self._jinja_env is not None:
            try:
                template = self._jinja_env.get_template(DAILY_LOG_TEMPLATE)
                return template.render(**context)
            except TemplateNotFound:
                logger.warning(
                    "Template '%s' not found. Using fallback.", DAILY_LOG_TEMPLATE
                )

        return self._fallback_template(context)

    @staticmethod
    def _fallback_template(context: dict[str, object]) -> str:
        """Generate a basic daily log when no Jinja2 template is available.

        Args:
            context: Template context dict with date info and sections.

        Returns:
            Formatted markdown string.
        """
        sections = context.get("sections", LOG_SECTIONS)
        lines = [
            f"# Daily Log — {context['display_date']}",
            "",
            f"**Date:** {context['date']}  ",
            f"**Day:** {context['day_of_week']}",
            "",
            "---",
            "",
        ]
        for section in sections:  # type: ignore[union-attr]
            lines.extend([f"## {section}", "", "- ", "", "---", ""])

        lines.append(
            f"*Generated by [GitHub Streak AI](https://github.com/yourusername/github-streak-ai)*"
        )
        return "\n".join(lines) + "\n"

    def create_daily_log(self, target_date: date | None = None) -> Path:
        """Create a new daily log file from the template.

        If the file already exists, returns the existing path without overwriting.

        Args:
            target_date: Date for the log. Defaults to today.

        Returns:
            Path to the created (or existing) log file.
        """
        target_date = target_date or date.today()
        log_path = self._get_log_path(target_date)

        if log_path.exists():
            logger.info("Log already exists for %s at %s", target_date, log_path)
            return log_path

        log_path.parent.mkdir(parents=True, exist_ok=True)
        content = self._render_template(target_date)
        log_path.write_text(content, encoding="utf-8")
        logger.info("Created daily log for %s at %s", target_date, log_path)
        return log_path

    def get_log(self, target_date: date) -> str:
        """Read the contents of a daily log.

        Args:
            target_date: The date of the log to read.

        Returns:
            The markdown content of the log.

        Raises:
            LogNotFoundError: If no log exists for the given date.
        """
        log_path = self._get_log_path(target_date)
        if not log_path.exists():
            raise LogNotFoundError(
                f"No log found for {target_date.strftime(DATE_FORMAT)}. "
                f"Expected at: {log_path}"
            )
        try:
            return log_path.read_text(encoding="utf-8")
        except UnicodeDecodeError as exc:
            raise LogCorruptedError(
                f"Log file at {log_path} contains invalid encoding: {exc}"
            ) from exc

    def update_log(self, target_date: date, content: str) -> Path:
        """Write new content to a daily log, creating it if necessary.

        Args:
            target_date: The date of the log to update.
            content: The full markdown content to write.

        Returns:
            Path to the updated log file.
        """
        log_path = self._get_log_path(target_date)
        log_path.parent.mkdir(parents=True, exist_ok=True)
        log_path.write_text(content, encoding="utf-8")
        logger.info("Updated log for %s at %s", target_date, log_path)
        return log_path

    def update_section(self, target_date: date, section: str, content: str) -> Path:
        """Update a specific section of an existing daily log.

        Args:
            target_date: The date of the log to update.
            section: The section header (e.g., "AI Summary").
            content: The new content for the section.

        Returns:
            Path to the updated log file.

        Raises:
            LogNotFoundError: If the log doesn't exist.
            LogError: If the section is not found in the log.
        """
        existing = self.get_log(target_date)

        # Match the section pattern: ## Section\n\n<content>\n\n---
        pattern = rf"(## {re.escape(section)}\n\n)(.*?)(\n\n---)"
        replacement = rf"\g<1>{content}\g<3>"
        updated, count = re.subn(pattern, replacement, existing, flags=re.DOTALL)

        if count == 0:
            raise LogError(
                f"Section '{section}' not found in log for {target_date.strftime(DATE_FORMAT)}."
            )

        return self.update_log(target_date, updated)

    def log_exists(self, target_date: date) -> bool:
        """Check whether a log file exists for the given date.

        Args:
            target_date: Date to check.

        Returns:
            True if the log file exists.
        """
        return self._get_log_path(target_date).exists()

    def list_logs(self) -> list[Path]:
        """List all log files sorted by date (ascending).

        Returns:
            Sorted list of log file paths.
        """
        logs = sorted(self._logs_dir.rglob("*.md"))
        return logs

    def get_log_dates(self) -> list[date]:
        """Get all dates that have a log file.

        Returns:
            Sorted list of dates.
        """
        dates: list[date] = []
        for log_path in self.list_logs():
            try:
                date_str = log_path.stem  # YYYY-MM-DD
                parsed = datetime.strptime(date_str, DATE_FORMAT).date()
                dates.append(parsed)
            except ValueError:
                logger.warning("Skipping file with unexpected name: %s", log_path)
        return sorted(dates)

    def get_logs_for_range(
        self, start: date, end: date
    ) -> list[tuple[date, str]]:
        """Get all logs within a date range (inclusive).

        Args:
            start: Start date (inclusive).
            end: End date (inclusive).

        Returns:
            List of (date, content) tuples for existing logs in the range.
        """
        results: list[tuple[date, str]] = []
        current = start
        while current <= end:
            if self.log_exists(current):
                try:
                    content = self.get_log(current)
                    results.append((current, content))
                except LogError as exc:
                    logger.warning("Error reading log for %s: %s", current, exc)
            current += timedelta(days=1)
        return results

    def get_total_log_count(self) -> int:
        """Get the total number of log files.

        Returns:
            Count of log files.
        """
        return len(self.list_logs())

    def get_log_path(self, target_date: date) -> Path:
        """Public accessor for the log path of a given date.

        Args:
            target_date: Date to get the path for.

        Returns:
            Full path to the log file (may not exist).
        """
        return self._get_log_path(target_date)
